export const REVIEW_TAIL_RULE: string
export const START_PROMPT: string
export const ADOPT_PROMPT: string
export const CHALLENGE_PROMPT: string
export const RESEARCH_PROMPT: string
export const RISKS_PROMPT: string
export const PLAN_PROMPT: string
export const BUILD_PROMPT: string
export const AUTOBUILD_PROMPT: string
export const ITERATE_PROMPT: string
export const DEEP_DIVE_PROMPT: string
