// Generates AGENTS.md: a one-way, read-only export of a project's SpecDrive
// house into its own codebase, for any coding tool that doesn't speak MCP.
// Pure rendering lives here so it can be unit-tested without Electron.
import fs from 'node:fs'
import path from 'node:path'
import type { Folder, FolderRule, Phase, ProjectBundle, Spec } from '../shared/types'

const PHASE_LABEL: Record<Phase, string> = {
  capture: 'Capturing the idea',
  challenge: 'Challenging the specs',
  research: 'Researching',
  risks: 'Weighing the hard parts',
  plan: 'Planning the build',
  build: 'Building',
  done: 'Built'
}

function isQuestion(s: Spec): boolean {
  return /^question\b/i.test(s.title.trim())
}

function ruleLine(r: FolderRule, opts: { overriddenBy?: string } = {}): string {
  const bits: string[] = []
  if (r.appliesTo) bits.push(`only for \`${r.appliesTo}\``)
  if (r.setBy) bits.push(`set by ${r.setBy === 'owner' ? 'the owner' : r.setBy.slice('agent:'.length)}`)
  if (r.confirmedByOwner) bits.push('owner approved')
  if (opts.overriddenBy) bits.push(`overridden by project rule "${opts.overriddenBy}"`)
  const meta = bits.length ? ` (${bits.join(' · ')})` : ''
  return `- **${r.title}**${meta}: ${r.content}`
}

/** Standing rules: folder rules first, then confirmed project-level decisions.
 *  A project decision whose title matches a folder rule's title overrides it —
 *  the folder rule is still listed, but marked overridden, never dropped silently. */
function standingRulesSection(folder: Folder | null | undefined, specs: Spec[]): string {
  const decisions = specs.filter((s) => s.category === 'decisions' && s.status === 'confirmed' && !isQuestion(s))
  const decisionTitles = new Map(decisions.map((d) => [d.title.trim().toLowerCase(), d.title]))
  const folderRules = folder?.rules ?? []
  const lines: string[] = []
  if (folderRules.length) {
    lines.push(`From the folder "${folder!.name}":`)
    for (const r of folderRules) {
      const overriddenBy = decisionTitles.get(r.title.trim().toLowerCase())
      lines.push(ruleLine(r, { overriddenBy }))
    }
  }
  if (decisions.length) {
    lines.push(folderRules.length ? '\nFrom this project (overrides the folder on the same topic):' : 'From this project:')
    for (const d of decisions) {
      lines.push(`- **${d.title}**: ${d.content.trim().split('\n')[0]}`)
    }
  }
  return lines.length ? lines.join('\n') : 'No standing rules recorded yet.'
}

function currentStateSection(bundle: ProjectBundle): string {
  const { project, specs, activity } = bundle
  const openQuestions = specs.filter((s) => s.category === 'decisions' && isQuestion(s)).length
  const lastActivity = activity[activity.length - 1]
  const lastTouched = lastActivity
    ? `${lastActivity.actor === 'agent' ? 'an agent' : 'the app'} · ${new Date(lastActivity.ts).toLocaleString()}`
    : `${new Date(project.updatedAt).toLocaleString()}`
  const lines = [
    `- Phase: **${PHASE_LABEL[project.phase]}**`,
    `- Open questions: ${openQuestions}`,
    `- Last touched by: ${lastTouched}`
  ]
  if (project.mode === 'existing') lines.push('- Mode: existing app — code is ground truth, specs cover the delta only')
  return lines.join('\n')
}

/** Title-only list of things this AGENTS.md export says "do not touch" without
 *  explicit new instruction: frozen or as-built areas the house has verified. */
function whatNotToTouchSection(specs: Spec[]): string {
  const frozen = specs.filter(
    (s) => (s.tags.includes('frozen') || s.tags.includes('as-built')) && s.confidence === 'confirmed'
  )
  if (!frozen.length) return 'Nothing marked frozen or as-built yet.'
  return frozen.map((s) => `- ${s.title}`).join('\n')
}

const HEADER = '<!-- Generated by SpecDrive — edit via SpecDrive, not here. Your changes will be overwritten. -->'

/** Pure render: bundle in, canonical AGENTS.md text out. No I/O. */
export function renderAgentsMd(bundle: ProjectBundle): string {
  const { project } = bundle
  return `${HEADER}
# AGENTS.md — ${project.name}

## What this house is
${project.oneLiner || 'A product being built with SpecDrive.'}
This file is a generated, read-only mirror of the SpecDrive board for tools that don't speak its MCP — the board itself is the source of truth.

## Standing rules
${standingRulesSection(bundle.folder, bundle.specs)}

## Current state
${currentStateSection(bundle)}

## What not to touch
${whatNotToTouchSection(bundle.specs)}

## How to work here
Connect the specdrive MCP server, call \`get_guidance\` first, and follow it — every task needs proof (what you ran, what you observed) before it counts as done.
`
}

const CLAUDE_MD_STUB = 'Read AGENTS.md — generated by SpecDrive.\n'

export interface AgentsMdSyncResult {
  wrote: boolean
  path?: string
  skipped?: 'no-codebase-path' | 'path-missing' | 'opted-out' | 'unchanged'
  claudeMdWritten?: boolean
}

/** Writes AGENTS.md (and a first-run CLAUDE.md stub) into one project's
 *  codebase, only when the content actually changed. Never overwrites an
 *  existing hand-written CLAUDE.md. */
export function syncOneAgentsMd(bundle: ProjectBundle): AgentsMdSyncResult {
  const dir = bundle.project.codebasePath
  if (!dir) return { wrote: false, skipped: 'no-codebase-path' }
  if (bundle.project.syncAgentsMd === false) return { wrote: false, skipped: 'opted-out' }
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return { wrote: false, skipped: 'path-missing' }

  const content = renderAgentsMd(bundle)
  const target = path.join(dir, 'AGENTS.md')
  let existing = ''
  try {
    existing = fs.readFileSync(target, 'utf8')
  } catch {
    // first write
  }
  let wrote = false
  if (existing !== content) {
    fs.writeFileSync(target, content)
    wrote = true
  }

  let claudeMdWritten = false
  const claudePath = path.join(dir, 'CLAUDE.md')
  if (!fs.existsSync(claudePath)) {
    fs.writeFileSync(claudePath, CLAUDE_MD_STUB)
    claudeMdWritten = true
  }

  return { wrote, path: target, skipped: wrote ? undefined : 'unchanged', claudeMdWritten }
}

/** Sync every bundle that has a codebase path. Each project is isolated —
 *  one bad path (deleted folder, permission error) must never block the rest. */
export function syncAllAgentsMd(bundles: ProjectBundle[]): void {
  for (const b of bundles) {
    if (!b.project.codebasePath) continue
    try {
      syncOneAgentsMd(b)
    } catch (err) {
      console.error(`[specdrive] AGENTS.md sync failed for "${b.project.name}":`, err)
    }
  }
}
